Improve record schema compiler errors
Force deeper evaluation of applications of `RecordReprs[Lazy]` and
`RecordDomains[Lazy]` by adding `& {}`.

Example error before, taken from a usage in another project:

```
src/persistence/GameSave.ts:58:5 - error TS2345: Argument of type '{ game: any; idk: any; }' is not assignable to parameter of type 'RecordDomains<{ game: Schema<Game, RecordReprs<{ world: Schema<World, RecordReprs<{ width: Schema<number, number>; height: Schema<number, number>; grid: Schema<Tile[][], { type: string; value: any; }[][]>; }>>; ... 5 more ...; completedTechs: Schema<...>; }>>; nextConversionPriority: Schema<...>; }>'.
  Object literal may only specify known properties, and 'idk' does not exist in type 'RecordDomains<{ game: Schema<Game, RecordReprs<{ world: Schema<World, RecordReprs<{ width: Schema<number, number>; height: Schema<number, number>; grid: Schema<Tile[][], { type: string; value: any; }[][]>; }>>; ... 5 more ...; completedTechs: Schema<...>; }>>; nextConversionPriority: Schema<...>; }>'.

58     idk: 0 as any,
```

Example error after:

```
src/persistence/GameSave.ts:58:5 - error TS2345: Argument of type '{ game: any; idk: any; }' is not assignable to parameter of type '{ game: Game; nextConversionPriority: number; }'.
  Object literal may only specify known properties, and 'idk' does not exist in type '{ game: Game; nextConversionPriority: number; }'.

58     idk: 0 as any,
```